import type { EnhanceMode } from '@/shared/enhance';

import { MODE_LABELS } from './messages';

export interface ResultLabel {
  title: string;
  note: string | null;
}

/**
 * Label for an enhanced result (specs/enhanced-photo-review: AI-enhanced labeling).
 * Captures beyond the native-pixel limit are AI-reconstructed in every mode; that note
 * replaces the Creative caveat.
 */
export function resultLabel(mode: EnhanceMode, aiReconstructed: boolean): ResultLabel {
  const modeTitle = MODE_LABELS[mode].title;
  if (aiReconstructed) {
    return {
      title: `AI-reconstructed (${modeTitle})`,
      note: 'Most detail was generated by AI and may not match reality.',
    };
  }
  return {
    title: `AI-enhanced (${modeTitle})`,
    note: mode === 'creative' ? "Creative mode may invent detail that doesn't match reality." : null,
  };
}
