import { resultLabel } from '../resultLabel';

describe('resultLabel', () => {
  it('labels ordinary results AI-enhanced with the mode', () => {
    expect(resultLabel('enhance', false)).toEqual({ title: 'AI-enhanced (Enhance)', note: null });
    expect(resultLabel('pro', false)).toEqual({ title: 'AI-enhanced (Pro)', note: null });
  });

  it('adds the invented-detail caveat in Creative mode', () => {
    expect(resultLabel('creative', false)).toEqual({
      title: 'AI-enhanced (Creative)',
      note: "Creative mode may invent detail that doesn't match reality.",
    });
  });

  it('labels captures beyond the native-pixel limit AI-reconstructed in every mode', () => {
    for (const [mode, title] of [
      ['enhance', 'Enhance'],
      ['pro', 'Pro'],
      ['creative', 'Creative'],
    ] as const) {
      expect(resultLabel(mode, true)).toEqual({
        title: `AI-reconstructed (${title})`,
        note: 'Most detail was generated by AI and may not match reality.',
      });
    }
  });
});
