import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { type SharedValue, useAnimatedReaction, withTiming } from 'react-native-reanimated';
import { scheduleOnRN } from 'react-native-worklets';

import type { LensInfo } from '@/camera/lenses';
import { zoomTier } from '@/camera/zoomTier';
import { colors, formatZoom, spacing } from '@/ui/theme';

const BEYOND_PRESETS = [10, 20, 30, 50, 100];

/** Picks first, middle and last so beyond-optical presets span the whole range. */
function spread<T>(items: T[], count: number): T[] {
  if (items.length <= count) return items;
  const middle = items[Math.floor((items.length - 1) / 2)];
  return [items[0], middle, items[items.length - 1]].slice(0, count);
}

/**
 * One preset per physical lens plus up to three beyond-optical presets, spread up to the
 * maximum (specs/zoom-capture: Zoom presets; extreme-zoom-100x design decision 2).
 */
export function zoomPresets(lensInfo: LensInfo, maxZoom: number): number[] {
  const lensPresets = [...new Set(lensInfo.lenses.map((l) => l.displayZoom))];
  const cap = lensInfo.opticalCapDisplay;
  let beyond = spread(
    BEYOND_PRESETS.filter((p) => p > cap * 1.5 && p <= maxZoom),
    3,
  );
  if (beyond.length === 0 && maxZoom > cap * 1.2) beyond = [Math.floor(maxZoom)];
  return [...lensPresets, ...beyond];
}

interface Props {
  displayZoom: SharedValue<number>;
  lensInfo: LensInfo;
  maxZoom: number;
  /** Past this zoom, most detail is generated (AI-reconstructed). */
  nativeLimit: number;
}

const BADGES = { ai: 'AI ZOOM', reconstructed: 'AI-RECONSTRUCTED' } as const;
const SPOKEN_TIER = { ai: ', beyond optical range, AI enhanced', reconstructed: ', AI reconstructed' } as const;

export function ZoomControls({ displayZoom, lensInfo, maxZoom, nativeLimit }: Props) {
  // Mirror the UI-thread zoom into React state at 0.1x resolution for the label.
  const [zoom, setZoom] = useState(1);
  useAnimatedReaction(
    () => Math.round(displayZoom.get() * 10) / 10,
    (current, previous) => {
      if (current !== previous) scheduleOnRN(setZoom, current);
    },
  );

  const cap = lensInfo.opticalCapDisplay;
  const tier = zoomTier(zoom, cap, nativeLimit);
  const presets = zoomPresets(lensInfo, maxZoom);

  return (
    <View style={styles.container} pointerEvents="box-none">
      {tier === 'reconstructed' && (
        <Text style={styles.hint} accessibilityRole="text">
          Most detail will be generated by AI. Brace your phone.
        </Text>
      )}
      <View
        style={[
          styles.readout,
          tier === 'ai' && styles.readoutBeyond,
          tier === 'reconstructed' && styles.readoutReconstructed,
        ]}
        accessibilityLabel={`Zoom ${formatZoom(zoom)}${tier === 'optical' ? '' : SPOKEN_TIER[tier]}`}
      >
        <Text
          style={[
            styles.readoutText,
            tier === 'ai' && styles.readoutTextBeyond,
            tier === 'reconstructed' && styles.readoutTextReconstructed,
          ]}
        >
          {formatZoom(zoom)}
        </Text>
        {tier !== 'optical' && (
          <Text style={[styles.badge, tier === 'reconstructed' && styles.badgeReconstructed]}>{BADGES[tier]}</Text>
        )}
      </View>
      <View style={styles.presets}>
        {presets.map((preset) => {
          const active = Math.abs(zoom - preset) / preset < 0.05;
          return (
            <Pressable
              key={preset}
              onPress={() => {
                displayZoom.set(withTiming(preset, { duration: 300 }));
              }}
              accessibilityRole="button"
              accessibilityLabel={`Zoom to ${formatZoom(preset)}`}
              style={[styles.preset, active && styles.presetActive, preset > cap && styles.presetBeyond]}
            >
              <Text style={[styles.presetText, active && styles.presetTextActive]}>{formatZoom(preset)}</Text>
            </Pressable>
          );
        })}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { alignItems: 'center', gap: spacing.md },
  readout: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    backgroundColor: colors.surface,
  },
  readoutBeyond: { borderWidth: 1, borderColor: colors.beyondOptical },
  readoutReconstructed: { borderWidth: 1, borderColor: colors.reconstructed },
  readoutText: { color: colors.accent, fontSize: 16, fontWeight: '700', fontVariant: ['tabular-nums'] },
  readoutTextBeyond: { color: colors.beyondOptical },
  readoutTextReconstructed: { color: colors.reconstructed },
  hint: {
    color: colors.text,
    fontSize: 13,
    backgroundColor: colors.surface,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 999,
    overflow: 'hidden',
  },
  badge: { color: colors.beyondOptical, fontSize: 10, fontWeight: '800', letterSpacing: 1 },
  badgeReconstructed: { color: colors.reconstructed },
  presets: {
    flexDirection: 'row',
    gap: spacing.xs,
    padding: spacing.xs,
    borderRadius: 999,
    backgroundColor: colors.surface,
  },
  preset: { minWidth: 40, height: 40, borderRadius: 20, alignItems: 'center', justifyContent: 'center' },
  presetActive: { backgroundColor: 'rgba(255,255,255,0.15)' },
  presetBeyond: { borderWidth: StyleSheet.hairlineWidth, borderColor: colors.beyondOptical },
  presetText: { color: colors.text, fontSize: 13, fontWeight: '600' },
  presetTextActive: { color: colors.accent },
});
